import { Metadata } from 'next';
import { getTermBySlug, getAllTerms, JargonTerm } from '@/lib/dictionary';
import Link from 'next/link';

type Props = {
    params: Promise<{ term: string }>;
};

// 1. Dynamic Meta Titles & OpenGraph (Click-Bait Schema)
export async function generateMetadata({ params }: Props): Promise<Metadata> {
    const { term } = await params;
    const termData = getTermBySlug(term);

    // Provide a fallback if the term isn't found
    const displayTerm = termData ? termData.term : term.charAt(0).toUpperCase() + term.slice(1);
    const title = `${displayTerm} Meaning: What your boss is actually saying | Un-gloss`;
    const description = termData ? termData.theTruth : `Uncover the real meaning behind the corporate jargon "${displayTerm}". Plain speak for the modern workplace.`;

    return {
        title: title,
        description: description,
        openGraph: {
            title: title,
            description: description,
            type: 'article',
            url: `https://www.un-gloss.com/meaning/${term}`,
            // In the future, this image can be dynamically generated by Vercel OG image generation (e.g. /api/og?term=${termData.term})
            images: [
                {
                    url: 'https://www.un-gloss.com/og-default.jpg',
                    width: 1200,
                    height: 630,
                    alt: `${displayTerm} before and after translation`,
                },
            ],
            siteName: 'Un-gloss',
        },
        twitter: {
            card: 'summary_large_image',
            title: title,
            description: description,
        }
    };
}

export default async function TermDefinitionPage({ params }: Props) {
    const { term } = await params;
    const termData = getTermBySlug(term);

    if (!termData) {
        return (
            <div className="min-h-screen flex flex-col items-center justify-center p-8 text-center" style={{ color: "var(--signal-white)" }}>
                <h1 className="text-4xl font-bold mb-4">404 - Term Not Found</h1>
                <p className="text-xl mb-8" style={{ color: "var(--text-muted)" }}>We haven't un-glossed "{term}" yet, but we're working on it.</p>
                <Link href="/" className="action-button btn-ungloss" style={{ textDecoration: "none", display: "inline-block", padding: "12px 24px" }}>
                    TRY THE FULL TRANSLATOR
                </Link>
            </div>
        );
    }

    // 2. JSON-LD Schema (SoftwareApplication & Dictionary)
    const jsonLd = {
        "@context": "https://schema.org",
        "@graph": [
            {
                "@type": "SoftwareApplication",
                "name": "Un-gloss",
                "applicationCategory": "UtilitiesApplication",
                "operatingSystem": "Any",
                "description": "An AI-powered translator that strips away corporate jargon and reveals the blunt truth behind business communications.",
                "url": "https://www.un-gloss.com",
            },
            {
                "@type": "DefinedTermSet",
                "@id": "https://www.un-gloss.com/meaning",
                "name": "The Hall of Shame: Corporate Jargon Dictionary",
                "hasDefinedTerm": {
                    "@type": "DefinedTerm",
                    "termCode": termData.slug,
                    "name": termData.term,
                    "description": termData.theTruth
                }
            }
        ]
    };

    // Construct related terms list
    const relatedTermsData = termData.relatedTerms
        .map(slug => getTermBySlug(slug))
        .filter((t): t is JargonTerm => t !== undefined);

    return (
        <div style={{ minHeight: "100vh", display: "flex", flexDirection: "column", padding: "40px 24px" }}>
            {/* Inject JSON-LD Schema */}
            <script
                type="application/ld+json"
                dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }}
            />

            <main style={{ flex: 1, maxWidth: "800px", margin: "0 auto", width: "100%" }}>
                {/* The Template: Definitions */}
                <div style={{ display: "flex", flexDirection: "column", gap: "32px", marginBottom: "48px" }}>
                    
                    {/* The Corporate Definition (Satirical) */}
                    <div className="glass-panel" style={{ padding: "32px", border: "1px solid rgba(255,255,255,0.1)", background: "rgba(0,0,0,0.3)" }}>
                        <h2 style={{ fontSize: "0.9rem", color: "var(--text-muted)", textTransform: "uppercase", letterSpacing: "0.05em", marginBottom: "16px" }}>
                            // The Fog (Corporate Definition)
                        </h2>
                        <p style={{ fontSize: "1.2rem", color: "var(--text-muted)", fontFamily: "'Roboto Mono', monospace", fontStyle: "italic", lineHeight: "1.6" }}>
                            "{termData.corporateDefinition}"
                        </p>
                    </div>

                    {/* The Un-glossed Reality (The Truth) */}
                    <div className="glass-panel" style={{ padding: "32px", borderLeft: "4px solid var(--warning-orange)", background: "rgba(255, 87, 34, 0.05)" }}>
                        <h2 style={{ fontSize: "0.9rem", color: "var(--warning-orange)", textTransform: "uppercase", letterSpacing: "0.05em", fontWeight: "bold", marginBottom: "16px" }}>
                            // The Clarity (Un-glossed Reality)
                        </h2>
                        <p className="human-text" style={{ fontSize: "1.4rem", lineHeight: "1.5" }}>
                            "{termData.theTruth}"
                        </p>
                    </div>

                </div>

                {/* Call to Action */}
                <div style={{ textAlign: "center", marginBottom: "48px", padding: "40px", background: "url('/noise.png'), linear-gradient(135deg, rgba(0, 123, 255, 0.1) 0%, rgba(255, 87, 34, 0.05) 100%)", borderRadius: "16px", border: "1px solid var(--glass-border)" }}>
                    <h3 style={{ fontSize: "1.5rem", color: "var(--signal-white)", marginBottom: "16px", fontWeight: "bold" }}>
                        Is your inbox full of this garbage?
                    </h3>
                    <p style={{ color: "var(--text-muted)", marginBottom: "24px" }}>
                        Paste any corporate email or Slack message to instantly strip away the B.S. and reveal what your coworkers are actually saying.
                    </p>
                    <Link href="/" className="action-button btn-ungloss" style={{ textDecoration: "none", display: "inline-block", padding: "16px 32px", fontSize: "1.1rem", fontWeight: "bold" }}>
                        TRY THE FULL TRANSLATOR
                    </Link>
                </div>

                {/* Internal Linking Logic: Related Terms Widget */}
                {relatedTermsData.length > 0 && (
                    <div style={{ borderTop: "1px solid var(--glass-border)", paddingTop: "32px" }}>
                        <h4 style={{ fontSize: "1.2rem", color: "var(--signal-white)", marginBottom: "24px" }}>
                            Related Jargon (People Also Read)
                        </h4>
                        <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fill, minmax(200px, 1fr))", gap: "16px" }}>
                            {relatedTermsData.map(related => (
                                <Link 
                                    key={related.slug} 
                                    href={`/meaning/${related.slug}`}
                                    style={{ 
                                        textDecoration: "none", 
                                        padding: "16px", 
                                        background: "rgba(255,255,255,0.02)", 
                                        border: "1px solid var(--glass-border)", 
                                        borderRadius: "8px",
                                        transition: "all 0.2s ease",
                                        color: "var(--electric-blue)",
                                        fontSize: "1rem",
                                        fontWeight: "500"
                                    }}
                                    onMouseOver={(e) => {
                                        e.currentTarget.style.borderColor = "var(--electric-blue)";
                                        e.currentTarget.style.background = "rgba(0, 123, 255, 0.05)";
                                    }}
                                    onMouseOut={(e) => {
                                        e.currentTarget.style.borderColor = "var(--glass-border)";
                                        e.currentTarget.style.background = "rgba(255,255,255,0.02)";
                                    }}
                                >
                                    {related.term} →
                                </Link>
                            ))}
                        </div>
                    </div>
                )}
            </main>
        </div>
    );
}
